# Generated by Django 5.2.8 on 2025-12-03 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEMITIDO', 'Demitido')], default='ATIVO', max_length=10)),
                ('data_admissao', models.DateField(default=django.utils.timezone.now)),
                ('data_demissao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CONTRATADO', 'Contratado'), ('DEMITIDO', 'Demitido'), ('REATIVADO', 'Reativado'), ('TRANSFERIDO', 'Transferido de unidade')], max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Histórico do Funcionário',
                'verbose_name_plural': 'Históricos dos Funcionários',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unidade_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.unidadetrabalho'),
        ),
    ]
