# Generated by Django 5.2.8 on 2025-12-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='unidade_trabalho',
            field=models.CharField(choices=[('VILA_OLIMPIA', 'Vila Olímpia'), ('ITAPEVI', 'Itapevi'), ('GARUVA', 'Garuva'), ('NAVEGANTES_CD1', 'Navegantes CD1'), ('NAVEGANTES_CD2', 'Navegantes CD2')], default='MATRIZ', max_length=50),
        ),
        migrations.DeleteModel(
            name='UnidadeTrabalho',
        ),
    ]
