# Generated by Django 5.2.8 on 2025-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_unidade_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='unidade_trabalho',
            field=models.CharField(choices=[('VILA_OLIMPIA', 'Vila Olímpia'), ('ITAPEVI', 'Itapevi'), ('GARUVA', 'Garuva'), ('NAVEGANTES_CD1', 'Navegantes CD01'), ('NAVEGANTES_CD2', 'Navegantes CD02')], default='MATRIZ', max_length=50),
        ),
    ]
