# Generated by Django 5.2.8 on 2025-12-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_dispositivo', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('COLETOR', 'Coletor'), ('IMPRESSORA', 'Impressora')], max_length=20)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em manutenção')], default='DISPONIVEL', max_length=20)),
                ('status_antes_manutencao', models.CharField(blank=True, choices=[('DISPONIVEL', 'Disponível'), ('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em manutenção')], max_length=20, null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='funcionarios.funcionario')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ManutencaoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name': 'Manutenção de Dispositivo',
                'verbose_name_plural': 'Manutenções de Dispositivos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
