# Generated by Django 5.2.8 on 2025-12-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_equipamento_aux', models.CharField(choices=[('MOUSE', 'Mouse'), ('TECLADO', 'Teclado'), ('HEADSET', 'Headset'), ('FONTE', 'Fonte'), ('MONITOR', 'Monitor')], max_length=20)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em manutenção')], default='DISPONIVEL', max_length=20)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.dispositivo')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Equipamento Auxiliar',
                'verbose_name_plural': 'Equipamentos Auxiliares',
                'ordering': ['nome'],
            },
        ),
    ]
