# Generated by Django 5.2.8 on 2025-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentoauxiliar',
            name='tipo_equipamento_aux',
            field=models.CharField(choices=[('MOUSE', 'Mouse'), ('TECLADO', 'Teclado'), ('HEADSET', 'Headset'), ('MONITOR', 'Monitor')], max_length=20),
        ),
    ]
